os: linux
dist: xenial
arch:
  - arm64   # ARMv8
  - amd64
language: cpp
compiler: 
  - gcc
  - clang
jobs:
  include: 
    - arch: ppc64le
      compiler: gcc
script: chmod +x ./build.sh && ./build.sh
